// <auto-generated />
using System;
using Atria.Core.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Atria.Core.Data.Migrations
{
    [DbContext(typeof(AtriaDbContext))]
    [Migration("20260202121648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Atria.Core.Data.Entities.Deploys.Deploy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FeedId");

                    b.HasIndex("FeedId", "Version");

                    b.ToTable("Deploys");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Deploys.DeployStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeployId")
                        .HasColumnType("uuid");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeployId");

                    b.HasIndex("DeployId", "CreatedAt");

                    b.ToTable("DeployStatusChanges");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Feeds.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlockDelay")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("EndBlock")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("ErrorHandling")
                        .HasColumnType("integer");

                    b.Property<string>("FilterPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FunctionPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NetworkId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SearchContent")
                        .HasColumnType("text");

                    b.Property<decimal?>("StartBlock")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("NetworkId");

                    b.HasIndex("SearchContent");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchContent"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchContent"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Status");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Feeds.FeedOutput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OutputId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OutputId");

                    b.HasIndex("FeedId", "OutputId")
                        .IsUnique();

                    b.ToTable("FeedOutputs");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Feeds.FeedStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FeedId");

                    b.HasIndex("FeedId", "CreatedAt");

                    b.ToTable("FeedStatusChanges");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Outputs.Output", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SearchContent")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SearchContent");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchContent"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchContent"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Type");

                    b.ToTable("Outputs");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Tags.FeedTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("FeedId", "TagId")
                        .IsUnique();

                    b.ToTable("FeedTags");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Tags.OutputTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OutputId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.HasIndex("OutputId", "TagId")
                        .IsUnique();

                    b.ToTable("OutputTags");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("Name", "Type")
                        .IsUnique()
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Deploys.Deploy", b =>
                {
                    b.HasOne("Atria.Core.Data.Entities.Feeds.Feed", "Feed")
                        .WithMany("Deploys")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Deploys.DeployStatusChange", b =>
                {
                    b.HasOne("Atria.Core.Data.Entities.Deploys.Deploy", "Deploy")
                        .WithMany("StatusChanges")
                        .HasForeignKey("DeployId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deploy");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Feeds.FeedOutput", b =>
                {
                    b.HasOne("Atria.Core.Data.Entities.Feeds.Feed", "Feed")
                        .WithMany("FeedOutputs")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atria.Core.Data.Entities.Outputs.Output", "Output")
                        .WithMany("FeedOutputs")
                        .HasForeignKey("OutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");

                    b.Navigation("Output");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Feeds.FeedStatusChange", b =>
                {
                    b.HasOne("Atria.Core.Data.Entities.Feeds.Feed", "Feed")
                        .WithMany("StatusChanges")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Tags.FeedTag", b =>
                {
                    b.HasOne("Atria.Core.Data.Entities.Feeds.Feed", "Feed")
                        .WithMany("FeedTags")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atria.Core.Data.Entities.Tags.Tag", "Tag")
                        .WithMany("FeedTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feed");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Tags.OutputTag", b =>
                {
                    b.HasOne("Atria.Core.Data.Entities.Outputs.Output", "Output")
                        .WithMany("OutputTags")
                        .HasForeignKey("OutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Atria.Core.Data.Entities.Tags.Tag", "Tag")
                        .WithMany("OutputTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Output");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Deploys.Deploy", b =>
                {
                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Feeds.Feed", b =>
                {
                    b.Navigation("Deploys");

                    b.Navigation("FeedOutputs");

                    b.Navigation("FeedTags");

                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Outputs.Output", b =>
                {
                    b.Navigation("FeedOutputs");

                    b.Navigation("OutputTags");
                });

            modelBuilder.Entity("Atria.Core.Data.Entities.Tags.Tag", b =>
                {
                    b.Navigation("FeedTags");

                    b.Navigation("OutputTags");
                });
#pragma warning restore 612, 618
        }
    }
}
