<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
        <PackageReference Include="StyleCop.Analyzers" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Atria.Common\Atria.Common.csproj" />
    </ItemGroup>

</Project>
